version: '3'

services:
  php:
    build: .
    ports:
      - "9000:80"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ems
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
